### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException

### ISSUE THREAD

**Issue by jmmortega** [Quobject/EngineIoClientDotNet#14]
I use SocketIOClientDotNet in Xamarin.And get this exception, when using websockets.

I don't know why happen this when check if contain elements. 

This is the stacktrace

at Quobject.Collections.Immutable.ImmutableDictionary>.get_Item(string key)

at Quobject.EngineIoClientDotNet.ComponentEmitter.Emitter.Off(string eventString, IListener fn)

at Quobject.SocketIoClientDotNet.Client.On.HandleImpl.Destroy()

at Quobject.SocketIoClientDotNet.Client.Manager.Cleanup()

at Quobject.SocketIoClientDotNet.Client.Manager.c_DisplayClass3.b_1(object data)

at Quobject.EngineIoClientDotNet.ComponentEmitter.ListenerImpl.Call(object[] args)

at Quobject.EngineIoClientDotNet.ComponentEmitter.Emitter.Emit(string eventString, object[] args)

at Quobject.EngineIoClientDotNet.Client.Socket.OnError(Exception exception)

at Quobject.EngineIoClientDotNet.Client.Socket.EventErrorListener.Call(object[] args)

at Quobject.EngineIoClientDotNet.ComponentEmitter.Emitter.Emit(string eventString, object[] args)

at Quobject.EngineIoClientDotNet.Client.Transport.OnError(string message, Exception exception)

at Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.DoPollEventErrorListener.Call(object[] args)

at Quobject.EngineIoClientDotNet.ComponentEmitter.Emitter.Emit(string eventString, object[] args)

at Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.XHRRequest.OnError(Exception err)

at Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.XHRRequest.Create()

at Quobject.EngineIoClientDotNet.Client.Transports.PollingXHR.DoPoll()

at Quobject.EngineIoClientDotNet.Client.Transports.Polling.Poll()

at Quobject.EngineIoClientDotNet.Client.Transports.Polling.DoOpen()

at Quobject.EngineIoClientDotNet.Client.Transport.Open()

at Quobject.EngineIoClientDotNet.Client.Socket.c_DisplayClass1.b_0()

at System.Threading.Tasks.Task.InnerInvoke()

at System.Threading.Tasks.Task.Execute()

Any suggestion?

**Comment by ducas** [comment]
i'm also getting this...

@jmmortega did you resolve it?

**Comment by mattqs** [comment]
The commit https://github.com/Quobject/EngineIoClientDotNet/commit/90dcb58f13ad6577630358ebf02c22ea68e53a03 should fix this problem.

**Comment by ducas** [comment]
@mattqs looks good. will it go into a nuget release any time soon or is there a build i can grab?

**Comment by mattqs** [comment]
This is now in nuget release:
https://www.nuget.org/packages/SocketIoClientDotNet/0.9.13

**Comment by ducas** [comment]
Excellent! I'll give it a go today. Thanks!
