### ISSUE TITLE
System.NullReferenceException Client Socket OnClose

### ISSUE THREAD

**Issue by jmmortega** [Quobject/EngineIoClientDotNet#15]
When using in mono, get a NullException in OnClose.

https://github.com/Quobject/EngineIoClientDotNet/blob/146fa0e95d4c97aedce887ba46bef2c85a6232df/Src/EngineIoClientDotNet.mono/Client/Socket.cs#L1032

at Quobject.EngineIoClientDotNet.Client.Socket.OnClose(string reason, Exception desc)

at Quobject.EngineIoClientDotNet.Client.Socket.Close()

at Quobject.SocketIoClientDotNet.Client.Manager.<>c__DisplayClass5.<Open>b__2()

at Quobject.EngineIoClientDotNet.Thread.EasyTimer.<>c__DisplayClass1.<SetTimeout>b__0()

at System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(object state)

at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state)

at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)

at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, object state, ref Task currentTask)

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

at System.Threading.Tasks.AwaitTaskContinuation.<ThrowAsyncIfNecessary>m__0(object s)

**Comment by trandangninh** [comment]
@jmmortega  do you find any solution? i meet same issue here

**Comment by mattqs** [comment]
The commit 90dcb58 should fix this problem.
