### ISSUE TITLE
InvalidOperationException: Collection was modified in WebSocket.Write

### ISSUE THREAD

**Issue by gamer3dx** [Quobject/EngineIoClientDotNet#20]
I'm using SocketIoClientDotNet 0.9.13 with EngineIoClientDotNet 0.9.22.

My code just connects to server via IO.Socket and sends message via "emit" method every 60 seconds.

And I'v caught this exception with stacktrace inside WebSocket transport:
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Quobject.EngineIoClientDotNet.Client.Transports.WebSocket.Write(List`1 packets)
   at Quobject.EngineIoClientDotNet.Client.Transport.Send(List`1 packets)
   at Quobject.EngineIoClientDotNet.Client.Socket.Flush()
   at Quobject.EngineIoClientDotNet.Client.Socket.SendPacket(Packet packet, Action fn)
   at Quobject.EngineIoClientDotNet.Client.Socket.<SetPing>b__64_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Quobject.EngineIoClientDotNet.Client.Transports.WebSocket.Write(List`1 packets)
   at Quobject.EngineIoClientDotNet.Client.Transport.Send(List`1 packets)
   at Quobject.EngineIoClientDotNet.Client.Socket.Flush()
   at Quobject.EngineIoClientDotNet.Client.Socket.SendPacket(Packet packet, Action fn)
   at Quobject.EngineIoClientDotNet.Client.Socket.<SetPing>b__64_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```
Any ideas or fixes?

**Comment by gamer3dx** [comment]
Fixed in #21
