### ISSUE TITLE
KeyNotFoundException: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by GMetaxakis** [Quobject/EngineIoClientDotNet#46]
do we have any workaround on a crass like that?
 no clue where and why it happens
```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at Quobject.EngineIoClientDotNet.ComponentEmitter.Emitter.Emit(String eventString, Object[] args)
   at Quobject.EngineIoClientDotNet.Client.Socket.OnError(Exception exception)
   at Quobject.EngineIoClientDotNet.ComponentEmitter.Emitter.Emit(String eventString, Object[] args)
   at Quobject.EngineIoClientDotNet.Client.Transport.OnError(String message, Exception exception)
   at WebSocket4Net.WebSocket.client_Error(Object sender, ErrorEventArgs e)
   at SuperSocket.ClientEngine.TcpClientSession.ProcessConnect(Socket socket, Object state, SocketAsyncEventArgs e, Exception exception)
   at SuperSocket.ClientEngine.ConnectAsyncExtension.SocketAsyncEventCompleted(Object sender, SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(Exception exception, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.MultipleConnectAsync.Fail(Boolean sync, Exception e)
   at System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(IAsyncResult result, Boolean sync)
   at System.Net.Sockets.MultipleConnectAsync.DnsCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Dns.ResolveCallback(Object context)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by MeTaXaS4** [comment]
@mattqs can I do anything to handle that kind of crashes, or do I have to wait for an update?

**Comment by mattqs** [comment]
Please submit a pull request.
